name: units_converter
description: Simple and light units conversion package for all your needs.
version: 0.2.0
homepage: https://github.com/ferraridamiano/units_converter
# homepage: https://www.example.com

environment:
  sdk: '>=2.10.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
