name: units_converter
description: Simple and light units conversion package for all your needs.
version: 0.2.0+2
homepage: https://github.com/ferraridamiano/units_converter

environment:
  sdk: '>=2.12.0-259.9.beta <3.0.0'

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
