name: Test

on:
  [push, pull_request]:
    branches:
      test

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Dart
      uses: cedx/setup-dart@v2.5.0
      with:
        release-channel: beta

    - name: Dart version
      run: dart --version

    - name: Download pub dependencies
      run: dart pub get

    - name: Run tests
      run: dart test