name: Test

on:
  push:
    branches:
      main
  pull_request:
    branches:
      main

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup Dart
      uses: dart-lang/setup-dart@v1.2

    - name: Dart version
      run: dart --version

    - name: Download pub dependencies
      run: dart pub get

    - name: Run tests
      run: dart test